### ISSUE TITLE
some problem i met about the config

### ISSUE THREAD

**Issue by 234424169** [klugjo/hexo-theme-clean-blog#41]
firstly i like the theme very much because it's really clean and fresh.But i met some problem can you help me to solve it?
1、the “menu_title” i have set in the config.yml, but the text on the top left is still "Configurable Title
", the setting is not work.
2、the github logo on the foot and the right top ,is link to your github,i want to link to my own github url.I write the "Github"-"url" in "menu" but it not work.
3、I don't know much about the category item,how do i use it?

**Comment by GHLandy** [comment]
![image](https://user-images.githubusercontent.com/14830914/29248338-46cae9c6-8048-11e7-9974-638a03fa1f9a.png)

For your first question, make sure that you have put your title in the right place  about picture,  I had met this because of wrong config. Your need also check for  colon, as every config item needs a Half Angle colon.

**Comment by 234424169** [comment]
![image](https://user-images.githubusercontent.com/15716467/29248596-94e94b92-804e-11e7-84e6-574b3d856c37.png)

i have check the colon,is a half angle colon.I have cuted the picture from my config file,is it something wrong?

**Comment by klugjo** [comment]
Hi,

Make sure you are putting this in the `_config.yml` inside your theme folder and not the main hexo config.

Are you getting any error during the generation ?

Are the other config entries working fine ?

**Comment by 234424169** [comment]
I'm new to hexo and this theme is my first theme.Orginally I have the _config.yml file in my blog directory generated by hexo and I edit the config on that.After getting your suggestion,I copy the config file into the theme directory but **it doesn't work**!
I havn't met error during the generation.

**Comment by klugjo** [comment]
there are 2 configs, one in the main directory called `_config.yml` and there is another one also called `_config.yml` inside the theme folder

Copy paste the following into the **THEME** `_config.yml`

```
# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Github:
    url: https://github.com/klugjo/hexo-theme-clean-blog
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Configurable Title

# URL of the Home page image
index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/klugjo/hexo-theme-clean-blog
gitlab_url:
linkedin_url:
mailto:
```

And modify what you need
