### ISSUE TITLE
top-right corner icon not perfectly aligned

### ISSUE THREAD

**Issue by cysiuaa** [klugjo/hexo-theme-clean-blog#48]
For the github icon at the top-right corner, it's not vertical aligned in Chrome, IE and Firefox. I tried to set 
```css
.fa-stack-2x {
  bottom: 0;
}
```
and it's perfectly aligned now.
